name: CI Terraform Reusable Workflow

on:
  workflow_call:
    inputs:
      working-dir:
        required: true
        type: string
      aws-region:
        required: true
        type: string
      tfcmt-target:
        required: true
        type: string
      is-masking:
        required: true
        type: boolean
      tf-backend-config-file-path:
        required: false
        type: string
        description: |-
          The path of the backend configuration file.
          The format is hcl or json.
      tf-var-file-path:
        required: false
        type: string
        description: |-
          The path of the var-file.
          The format is hcl or json.

    secrets:
      aws-account-name:
        required: true
      aws-account-id:
        required: true
      aws-iam-role-name:
        required: false
      aws-access-key-id:
        required: false
      aws-secret-access-key:
        required: false
      aws-session-token:
        required: false

      tf-backend-config-content:
        required: false
        description: |
          The content of backend configuration.
          The format is hcl or json.
      tf-var-file-content:
        required: false
        description: |
          The content of var-file.
          The format is hcl or json.

env:
  TF_BACKEND_CONFIG_FILE_PATH: /tmp/terraform_backend_config.file
  TF_VAR_FILE_PATH: /tmp/tfvar.file
  TF_VERSION: 1.7.4

jobs:
  ci-terraform:
    name: CI Terraform
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pull-requests: write

    defaults:
      run:
        working-directory: ${{ inputs.working-dir }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
      - name: PWD
        run: pwd

      - name: Masking
        if: ${{ inputs.is-masking }}
        run: |-
          # github actions
          echo "::add-mask::${{ secrets.aws-account-id }}"
          echo "::add-mask::${{ secrets.aws-account-name }}"
          # tfcmt
          echo "TFCMT_MASKS_SEPARATOR=," >> "$GITHUB_ENV"
          echo "TFCMT_MASKS=regexp:\\Q${{ secrets.aws-account-id }}\\E,regexp:\\Q${{ secrets.aws-account-name }}\\E" >> "$GITHUB_ENV"

      - name: Restore Terraform Cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ inputs.working-dir }}/.terraform
          key: terraform-${{ hashFiles(format('{0}/.terraform.lock.hcl', inputs.working-dir)) }}
          restore-keys: |
            terraform-

      - name: Put tf-backend-config
        env:
          _tf_backend_config_file_path: ${{ inputs.tf-backend-config-file-path }}
          _tf_backend_config_content: ${{ secrets.tf-backend-config-content }}
        run: |-
          if [ -n '${{ env._tf_backend_config_file_path }}' ] && [ -n '${{ env._tf_backend_config_content }}' ]; then
            echo "Both tf-backend-config-file-path and tf-backend-config-content are provided."
            echo "Either tf-backend-config-file-path or tf-backend-config-content must be provided."
            exit 1
          elif [ -n '${{ env._tf_backend_config_file_path }}' ]; then
            echo "inputs.tf-backend-config-file-path is provided."
            cp ${{ env._tf_backend_config_file_path }} ${{ env.TF_BACKEND_CONFIG_FILE_PATH }}
          elif [ -n '${{ env._tf_backend_config_content }}' ]; then
            echo "secrets.tf-backend-config-content is provided."
            echo '${{ env._tf_backend_config_content }}' > ${{ env.TF_BACKEND_CONFIG_FILE_PATH }}
          else
            echo "Both tf-backend-config-file-path and tf-backend-config-content are not provided."
            echo "Either tf-backend-config-file-path or tf-backend-config-content must be provided."
            exit 1
          fi
      - name: Put tf-var-file
        env:
          _tf_var_file_path: ${{ inputs.tf-var-file-path }}
          _tf_var_file_content: ${{ secrets.tf-var-file-content }}
        run: |-
          if [ -n '${{ env._tf_var_file_path }}' ] && [ -n '${{ env._tf_var_file_content }}' ]; then
            echo "Both tf-var-file-path and tf-var-file-content are provided."
            echo "Either tf-var-file-path or tf-var-file-content must be provided."
            exit 1
          elif [ -n '${{ env._tf_var_file_path }}' ]; then
            echo "inputs.tf-var-file-path is provided."
            cp ${{ env._tf_var_file_path }} ${{ env.TF_VAR_FILE_PATH }}
          elif [ -n '${{ env._tf_var_file_content }}' ]; then
            echo "secrets.tf-var-file-content is provided."
            echo '${{ env._tf_var_file_content }}' > ${{ env.TF_VAR_FILE_PATH }}
          else
            echo "Both tf-var-file-path and tf-var-file-content are not provided."
            echo "Either tf-var-file-path or tf-var-file-content must be provided."
            exit 1
          fi

      - name: Check Inputs or Secrets for AWS Credentials
        run: |-
          if [ -n "${{ secrets.aws-iam-role-name }}" ] && [ -n "${{ secrets.aws-access-key-id }}" ]; then
            echo "Both aws-iam-role-name and aws-access-key-id are provided."
            echo "Either aws-iam-role-name or aws-access-key-id must be provided."
            exit 1
          elif [ -n "${{ secrets.aws-iam-role-name }}" ]; then
            echo "aws-iam-role-name is provided."
          elif [ -n "${{ secrets.aws-access-key-id }}" ]; then
            echo "aws-access-key-id is provided."
          else
            echo "Neither aws-iam-role-name nor aws-access-key-id is provided."
            echo "Either aws-iam-role-name or aws-access-key-id must be provided."
            exit 1
          fi
      - name: Configure AWS credentials from IAM Role
        env:
          aws_iam_role_name: ${{ secrets.aws-iam-role-name }}
        if: ${{ env.aws_iam_role_name && env.aws_iam_role_name != '' }}
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.aws-account-id }}:role/${{ secrets.aws-iam-role-name }}
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-session-token: ${{ secrets.aws-session-token }}
          aws-region: ${{ inputs.aws-region }}
      - name: Configure AWS credentials from Access Key
        env:
          aws_access_key_id: ${{ secrets.aws-access-key-id }}
        if: ${{ env.aws_access_key_id && env.aws_access_key_id != '' }}
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-session-token: ${{ secrets.aws-session-token }}
          aws-region: ${{ inputs.aws-region }}

      - name: Install Terraform
        working-directory: .
        run: ./scripts/install_terraform.sh ${{ env.TF_VERSION }}
      - name: Install tfcmt
        if: ${{ !env.ACT }}
        working-directory: .
        run: |
          sudo curl -fL -o tfcmt.tar.gz https://github.com/suzuki-shunsuke/tfcmt/releases/download/"$TFCMT_VERSION"/tfcmt_linux_amd64.tar.gz
          sudo tar -C /usr/bin -xzf ./tfcmt.tar.gz
        env:
          TFCMT_VERSION: "v4.9.0"

      - name: Terraform Init
        run: |-
          terraform init -backend-config=${{ env.TF_BACKEND_CONFIG_FILE_PATH }}
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Plan on GitHub Actions
        if: ${{ !env.ACT }}
        run: |-
          tfcmt -var "target:${{ inputs.tfcmt-target }}" plan -patch -- terraform plan -lock=false -var-file=${{ env.TF_VAR_FILE_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform Plan on act
        if: ${{ env.ACT }}
        run: terraform plan -lock=false -var-file=${{ env.TF_VAR_FILE_PATH }}

      - name: Save Terraform Cache
        if: ${{ !env.ACT }}
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ inputs.working-dir }}/.terraform
          key: terraform-${{ hashFiles(format('{0}/.terraform.lock.hcl', inputs.working-dir)) }}
