name: Update Terraform

on:
  schedule:
    - cron: "0 2 * * 1"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  get_terraform_latest_version:
    runs-on: ubuntu-latest
    steps:
      - name: Get terraform latest version
        id: get_terraform_latest_version
        run: |-
          TF_LATEST_VERSION=$(\
            curl -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${GITHUB_TOKEN}" \
              https://api.github.com/repos/hashicorp/terraform/releases/latest \
            | jq -r '.tag_name' \
            | sed -e 's/^v//' \
          )
          echo "TF_LATEST_VERSION: $TF_LATEST_VERSION"
          echo "tf-latest-version=$TF_LATEST_VERSION" >> "$GITHUB_OUTPUT"

    outputs:
      version: ${{ steps.get_terraform_latest_version.outputs.tf-latest-version }}


  update_terraform:
    runs-on: ubuntu-latest
    container:
      image: minamijoyo/tfupdate:0.6.1

    needs: get_terraform_latest_version

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Display tfupdate version
        run: tfupdate --version

      - name: Execute tfupdate
        run: |-
          find . -path ./aws/terraform/**/_tf_provider.tf | xargs -n 1 -P 10 -I {} tfupdate terraform {}
          find . -path ./aws/terraform/**/_tf_provider.tf | xargs -n 1 -P 10 -I {} tfupdate provider aws {}

      - name: Update github action
        run: |-
          find .github/workflows/ -type f \
          | xargs -I {} sed -i "s/TF_VERSION: [0-9\.]*$/TF_VERSION: ${{ needs.get_terraform_latest_version.outputs.version }}/g" {}

      - name: Display diff
        id: display_diff
        run: |-
          git diff | cat
          # diffが存在する場合は exists_diff に true をセット
          if [ -n "$(git diff)" ]; then
            echo "exists_diff=true" >> "$GITHUB_ENV"
            echo "exists_diff=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit and Push
        id: commit_and_push
        if: env.exists_diff == 'true'
        run: |-
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git remote set-url origin https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

          branch_name=update-terraform#${{ needs.get_terraform_latest_version.outputs.version }}
          echo "branch_name=$branch_name" >> "$GITHUB_OUTPUT"
          git checkout -b $branch_name
          git add -u .
          git commit -m "Update terraform v${{ needs.get_terraform_latest_version.outputs.version }}"
          git push origin HEAD

    outputs:
      exists_diff: ${{ steps.display_diff.outputs.exists_diff }}
      branch_name: ${{ steps.commit_and_push.outputs.branch_name }}


  create_pull_request:
    runs-on: ubuntu-latest

    needs:
      - get_terraform_latest_version
      - update_terraform
    if: needs.update_terraform.outputs.exists_diff == 'true'

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Create pull request
        run: |-
          curl -X POST \
               -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${GITHUB_TOKEN}" \
               https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls \
               -d '{
                 "title": "Update terraform v${{ needs.get_terraform_latest_version.outputs.version }}",
                 "body": "This Pull Request craeted by GitHub Actions.",
                 "head": "${{ needs.update_terraform.outputs.branch_name }}",
                 "base": "${{ github.ref_name }}"
               }'
